micronaut:
  application:
    name: keyManagerGRPC
datasources:
  default:
    url: jdbc:mysql://localhost:3306/pixmanager?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'desafios'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update


client:
  erp:
    itau:
      url: http://localhost:9091/api/v1/